# __Reto 6: Procesamiento de datasets__

## Objetivo

Realizar operaciones de preprocesamiento sobre el dataset House Predicition Rent y alistarlo para entrenar un modelo de Machine Learning.

## Tarea 1

Leer la documentacion del dataset y conocer cada una de las variables y lo que representan

En este conjunto de datos encontrará una colección completa de información sobre más de 4700 propiedades residenciales disponibles, que incluyen casas, apartamentos y pisos ofrecidos en alquiler en India. Esto refleja la importante expansión experimentada en el sector de la vivienda de la India, que ha ido en paralelo a la trayectoria ascendente de los niveles de ingresos en el país. El conjunto de datos es rico en diversos atributos, como el número de dormitorios (BHK), precios de alquiler, tamaño de la propiedad, número de plantas, tipo de área, localidad, ciudad, estado del mobiliario, preferencias del inquilino, número de baños e información de contacto del punto de contacto correspondiente.

- BHK: Número de dormitorios, salón y cocina. 

- Rent: Alquiler de las casas/apartamentos/pisos. 

- Size: Tamaño de las casas/apartamentos/pisos en pies cuadrados. 

- Floor: Planta en la que se encuentran las casas/apartamentos/pisos y número total de plantas (Ejemplo: planta baja de 2, planta 3 de 5, etc.). 

- Area Type: Tamaño de las casas/apartamentos/pisos calculado en función de la superficie total, la superficie útil o la superficie construida. 

- Area Locality: Localidad de las casas/apartamentos/pisos. 

- City: Ciudad donde se encuentran las casas/apartamentos/pisos.

- Furnishing Status: Estado del mobiliario de las casas/apartamentos/pisos: amueblado, semi-amueblado o sin amueblar. 

- Tenant Preferred: Tipo de inquilino preferido por el propietario o agente. 

- Bathroom: Número de baños. 

- Point of Contact: Con quién debe ponerse en contacto para obtener más información sobre las casas/apartamentos/pisos.

## Tarea 2

Eliminar las columnas `Floor` y `Area Locality`.

In [1]:
# librerias
import numpy as np
import pandas as pd

In [2]:
# cargar datos
df = pd.read_csv('./House_Rent_Dataset.csv')
df.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

In [3]:
# eliminar los campos solicitados
df = df.drop(columns=['Floor', 'Area Locality'])
df.shape

(4746, 10)

## Tarea 3

Convertir el tipo de dato de la columna `Posted On` (De object a datetime).

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Posted On          4746 non-null   object
 1   BHK                4746 non-null   int64
 2   Rent               4746 non-null   int64
 3   Size               4746 non-null   int64
 4   Area Type          4746 non-null   object
 5   City               4746 non-null   object
 6   Furnishing Status  4746 non-null   object
 7   Tenant Preferred   4746 non-null   object
 8   Bathroom           4746 non-null   int64
 9   Point of Contact   4746 non-null   object
dtypes: int64(4), object(6)
memory usage: 370.9+ KB

In [5]:
# convertir a datetime
df['Posted On'] = pd.to_datetime(df['Posted On'], format='%Y-%m-%d')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Posted On          4746 non-null   datetime64[ns]
 1   BHK                4746 non-null   int64
 2   Rent               4746 non-null   int64
 3   Size               4746 non-null   int64
 4   Area Type          4746 non-null   object
 5   City               4746 non-null   object
 6   Furnishing Status  4746 non-null   object
 7   Tenant Preferred   4746 non-null   object
 8   Bathroom           4746 non-null   int64
 9   Point of Contact   4746 non-null   object
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 370.9+ KB

## Tarea 4

Aplicar codificación One Hot sobre las siguientes variables: `Area Type`, `City`, `Furnishing Status`, `Tenant Preferred`, `Point of Contact`

In [6]:
# aplicar codificacion
vars_nominal = pd.get_dummies(df[['Area Type', 'City', 'Furnishing Status', 'Tenant Preferred', 'Point of Contact']])
vars_nominal

,Area Type_Built Area,Area Type_Carpet Area,Area Type_Super Area,City_Bangalore,City_Chennai,City_Delhi,City_Hyderabad,City_Kolkata,City_Mumbai,Furnishing Status_Furnished,Furnishing Status_Semi-Furnished,Furnishing Status_Unfurnished,Tenant Preferred_Bachelors,Tenant Preferred_Bachelors/Family,Tenant Preferred_Family,Point of Contact_Contact Agent,Point of Contact_Contact Builder,Point of Contact_Contact Owner
0,False,False,True,False,False,False,False,True,False,False,False,True,False,True,False,False,False,True
1,False,False,True,False,False,False,False,True,False,False,True,False,False,True,False,False,False,True
2,False,False,True,False,False,False,False,True,False,False,True,False,False,True,False,False,False,True
3,False,False,True,False,False,False,False,True,False,False,False,True,False,True,False,False,False,True
4,False,True,False,False,False,False,False,True,False,False,False,True,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4741,False,True,False,False,False,False,True,False,False,False,True,False,False,True,False,False,False,True
4742,False,False,True,False,False,False,True,False,False,False,True,False,False,True,False,False,False,True
4743,False,True,False,False,False,False,True,False,False,False,True,False,False,True,False,True,False,False
4744,False,True,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False,False
4745,False,True,False,False,False,False,True,False,False,False,False,True,True,False,False,False,False,True

In [7]:
# concatenar variables codificadas con el dataframe original
df = pd.concat([df, vars_nominal], axis=1)
df.sample(5)

,Posted On,BHK,Rent,Size,Area Type,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact,...,City_Mumbai,Furnishing Status_Furnished,Furnishing Status_Semi-Furnished,Furnishing Status_Unfurnished,Tenant Preferred_Bachelors,Tenant Preferred_Bachelors/Family,Tenant Preferred_Family,Point of Contact_Contact Agent,Point of Contact_Contact Builder,Point of Contact_Contact Owner
772,2022-06-23,1,60000,500,Carpet Area,Mumbai,Furnished,Bachelors/Family,1,Contact Agent,...,True,True,False,False,False,True,False,True,False,False
99,2022-06-13,2,15000,900,Carpet Area,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Agent,...,False,False,True,False,False,True,False,True,False,False
2147,2022-07-06,2,13000,500,Carpet Area,Bangalore,Semi-Furnished,Bachelors,1,Contact Agent,...,False,False,True,False,True,False,False,True,False,False
3652,2022-05-20,2,15000,950,Super Area,Chennai,Semi-Furnished,Family,1,Contact Owner,...,False,False,True,False,False,False,True,False,False,True
1738,2022-05-14,3,32000,1800,Super Area,Bangalore,Semi-Furnished,Bachelors/Family,3,Contact Owner,...,False,False,True,False,False,True,False,False,False,True

## Tarea 5

Aplicar `MinMaxScaler` a las variables: `BHK`, `Size`, y `Bathroom`.

In [8]:
# librerias
from sklearn.preprocessing import MinMaxScaler

# instanciar el objeto minmaxscaler
scaler_minmax = MinMaxScaler()

# transformamos las variables seleccionadas con minmaxscaler
df[['BHK', 'Size', 'Bathroom']] = scaler_minmax.fit_transform(df[['BHK', 'Size', 'Bathroom']])
df.head()

,Posted On,BHK,Rent,Size,Area Type,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact,...,City_Mumbai,Furnishing Status_Furnished,Furnishing Status_Semi-Furnished,Furnishing Status_Unfurnished,Tenant Preferred_Bachelors,Tenant Preferred_Bachelors/Family,Tenant Preferred_Family,Point of Contact_Contact Agent,Point of Contact_Contact Builder,Point of Contact_Contact Owner
0,2022-05-18,0.2,10000,0.136421,Super Area,Kolkata,Unfurnished,Bachelors/Family,0.111111,Contact Owner,...,False,False,False,True,False,True,False,False,False,True
1,2022-05-13,0.2,20000,0.098874,Super Area,Kolkata,Semi-Furnished,Bachelors/Family,0.000000,Contact Owner,...,False,False,True,False,False,True,False,False,False,True
2,2022-05-16,0.2,17000,0.123905,Super Area,Kolkata,Semi-Furnished,Bachelors/Family,0.000000,Contact Owner,...,False,False,True,False,False,True,False,False,False,True
3,2022-07-04,0.2,10000,0.098874,Super Area,Kolkata,Unfurnished,Bachelors/Family,0.000000,Contact Owner,...,False,False,False,True,False,True,False,False,False,True
4,2022-05-09,0.2,7500,0.105131,Carpet Area,Kolkata,Unfurnished,Bachelors,0.000000,Contact Owner,...,False,False,False,True,True,False,False,False,False,True