# __Reto 5: Adicion de variables__

## Objetivo

Saber qué método de codificación usar cuando se enfrenta a variables categóricas nominales y ordinales

## Tarea 1

Cargar el dataset modificado Breast Cancer

In [24]:
# librerias
import pandas as pd
import numpy as np

In [25]:
# cargar datos
df = pd.read_excel('./breast-cancer-modified.xlsx', index_col=0)
df.sample(5)

        age menopause deg-malig  breast irradiat                  Class
40   30-39'  premeno'        3'   left'      no'     recurrence-events'
44   30-39'  premeno'        1'   left'      no'  no-recurrence-events'
192  60-69'     ge40'        3'   left'      no'     recurrence-events'
81   40-49'  premeno'        2'  right'      no'  no-recurrence-events'
173  50-59'  premeno'        1'  right'      no'     recurrence-events'

## Tarea 2

Aplicar la codificacion correspondiente dependiendo de la informacion de cada variable

__age: Ordinal__

In [26]:
df.age.unique()

array(["40-49'", "50-59'", "60-69'", "30-39'", "70-79'", "20-29'"],
      dtype=object)

In [27]:
# importar OrdinalEncoder
from sklearn.preprocessing import OrdinalEncoder

# instanciar el objeto ordinalencoder
# agregar en orden las categorias
encoder = OrdinalEncoder(categories=[["20-29'", "30-39'", "40-49'", "50-59'", "60-69'",  "70-79'"]])

# ajustar y transformar el encoder
age_ordinal = encoder.fit_transform(df[['age']])

# concatenar valores codificados el dataframe original
df['age_encoded'] = age_ordinal

df.sample(5)

,age,menopause,deg-malig,breast,irradiat,Class,age_encoded
200,30-39',premeno',2',left',no',no-recurrence-events',1.0
234,60-69',ge40',2',right',no',no-recurrence-events',4.0
90,60-69',ge40',1',right',no',recurrence-events',4.0
106,60-69',ge40',2',left',yes',recurrence-events',4.0
70,50-59',premeno',3',left',yes',recurrence-events',3.0

__Variables Nominales: menopause, breast, irradiat, Class__

In [28]:
# codificar todas las variables nominales en un mismo paso
var_nominal = pd.get_dummies(df[['menopause', 'breast', 'irradiat', 'Class']])
var_nominal

,menopause_ge40',menopause_lt40',menopause_premeno',breast_left',breast_right',irradiat_no',irradiat_yes',Class_no-recurrence-events',Class_recurrence-events'
0,False,False,True,False,True,True,False,False,True
1,True,False,False,False,True,True,False,True,False
2,True,False,False,True,False,True,False,False,True
3,False,False,True,False,True,False,True,True,False
4,False,False,True,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...
281,True,False,False,True,False,True,False,True,False
282,False,False,True,True,False,False,True,True,False
283,False,False,True,False,True,True,False,True,False
284,False,False,True,False,True,True,False,True,False
285,True,False,False,True,False,True,False,True,False

In [29]:
# concatenar variables codificadas al dataframe original
df = pd.concat([df, var_nominal], axis=1)
df.sample(5)

,age,menopause,deg-malig,breast,irradiat,Class,age_encoded,menopause_ge40',menopause_lt40',menopause_premeno',breast_left',breast_right',irradiat_no',irradiat_yes',Class_no-recurrence-events',Class_recurrence-events'
54,40-49',premeno',2',left',yes',no-recurrence-events',2.0,False,False,True,True,False,False,True,True,False
133,40-49',premeno',2',right',no',recurrence-events',2.0,False,False,True,False,True,True,False,False,True
244,40-49',premeno',1',left',no',no-recurrence-events',2.0,False,False,True,True,False,True,False,True,False
94,50-59',ge40',2',right',no',no-recurrence-events',3.0,True,False,False,False,True,True,False,True,False
171,50-59',ge40',3',right',no',recurrence-events',3.0,True,False,False,False,True,True,False,False,True

__deg-malig: Ordinal__

In [30]:
# obtener valores unicos de la variable deg-malig
df['deg-malig'].unique()

array(["3'", "1'", "2'"], dtype=object)

In [31]:
# instanciar el objeto ordinalencoder
# agregar en orden las categorias
encoder2 = OrdinalEncoder(categories=[["1'", "2'", "3'"]])

# ajustar y transformar el encoder
deg_ordinal = encoder2.fit_transform(df[['deg-malig']])

# concatenar valores codificados el dataframe original
df['deg_malig_encoded'] = deg_ordinal

df.sample(5)

,age,menopause,deg-malig,breast,irradiat,Class,age_encoded,menopause_ge40',menopause_lt40',menopause_premeno',breast_left',breast_right',irradiat_no',irradiat_yes',Class_no-recurrence-events',Class_recurrence-events',deg_malig_encoded
274,50-59',ge40',3',left',no',no-recurrence-events',3.0,True,False,False,True,False,True,False,True,False,2.0
101,50-59',premeno',2',left',no',recurrence-events',3.0,False,False,True,True,False,True,False,False,True,1.0
96,30-39',premeno',1',left',no',recurrence-events',1.0,False,False,True,True,False,True,False,False,True,0.0
234,60-69',ge40',2',right',no',no-recurrence-events',4.0,True,False,False,False,True,True,False,True,False,1.0
187,40-49',premeno',3',left',no',recurrence-events',2.0,False,False,True,True,False,True,False,False,True,2.0