# __Reto 9: Informe fundamentado en la visualizacion de datos__

## Objetivo

Realiza un informe donde se evalue la visualizacionb con cada uno de los connceptos aprendidos.

## Tarea 1

Vamos a trabajar con el dataset "House Prediction Rent"

In [22]:
# librerias
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Configuración visual
sns.set_theme(style='whitegrid')
plt.rcParams['figure.figsize'] = (10,6)

In [7]:
df = pd.read_csv('./House_Rent_Dataset.csv')
df.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

## Tarea 2

Procesar los datos

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Posted On          4746 non-null   object
 1   BHK                4746 non-null   int64
 2   Rent               4746 non-null   int64
 3   Size               4746 non-null   int64
 4   Floor              4746 non-null   object
 5   Area Type          4746 non-null   object
 6   Area Locality      4746 non-null   object
 7   City               4746 non-null   object
 8   Furnishing Status  4746 non-null   object
 9   Tenant Preferred   4746 non-null   object
 10  Bathroom           4746 non-null   int64
 11  Point of Contact   4746 non-null   object
dtypes: int64(4), object(8)
memory usage: 445.1+ KB

In [25]:
# mostrar valores nulos, si los hay
df.isnull().sum()

Posted On            0
BHK                  0
Rent                 0
Size                 0
Floor                0
Area Type            0
Area Locality        0
City                 0
Furnishing Status    0
Tenant Preferred     0
Bathroom             0
Point of Contact     0
dtype: int64

In [26]:
# mostrar duplicados, si los hay
df.duplicated().sum()

np.int64(0)

In [27]:
# Convertir fecha
df['Posted On'] = pd.to_datetime(df['Posted On'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Posted On          4746 non-null   datetime64[ns]
 1   BHK                4746 non-null   int64
 2   Rent               4746 non-null   int64
 3   Size               4746 non-null   int64
 4   Floor              4746 non-null   object
 5   Area Type          4746 non-null   object
 6   Area Locality      4746 non-null   object
 7   City               4746 non-null   object
 8   Furnishing Status  4746 non-null   object
 9   Tenant Preferred   4746 non-null   object
 10  Bathroom           4746 non-null   int64
 11  Point of Contact   4746 non-null   object
dtypes: datetime64[ns](1), int64(4), object(7)
memory usage: 445.1+ KB

In [28]:
df.Floor.unique()

array(['Ground out of 2', '1 out of 3', '1 out of 2', 'Ground out of 1',
       'Ground out of 4', '1 out of 4', '1 out of 1', 'Ground out of 3',
       '2 out of 3', '4 out of 5', '2 out of 2', '2 out of 5',
       '4 out of 14', '3 out of 3', '5 out of 5', '4 out of 4',
       '7 out of 8', '2 out of 4', '3 out of 4', '1 out of 5',
       '8 out of 5', 'Ground out of 6', '2 out of 1',
       'Upper Basement out of 4', 'Ground out of 5', '3 out of 5',
       '11 out of 19', '5 out of 10', '11 out of 14',
       'Lower Basement out of 2', '2 out of 7', '4 out of 10',
       '7 out of 10', '2 out of 13', '6 out of 7', '4 out of 7',
       '14 out of 14', '43 out of 78', '2 out of 8', '13 out of 18',
       '5 out of 12', '18 out of 24', '3 out of 7', '17 out of 31',
       '11 out of 21', '7 out of 19', '14 out of 23', '9 out of 20',
       'Upper Basement out of 9', '19 out of 24', '3 out of 21',
       '1 out of 22', '8 out of 8', '6 out of 12', '4 out of 58',
       'Upper Basement out of 16', '60 out of 66', '34 out of 48',
       '5 out of 8', '5 out of 14', '14 out of 40', '5 out of 7',
       '9 out of 22', '12 out of 18', '26 out of 44', '1 out of 8',
       '25 out of 42', '25 out of 41', '53 out of 78', 'Ground out of 7',
       '14 out of 20', '13 out of 20', '16 out of 23', '10 out of 18',
       '39 out of 60', '16 out of 21', '10 out of 32', '4 out of 8',
       '12 out of 24', '32 out of 41', '3 out of 30', '13 out of 21',
       '9 out of 29', '47 out of 89', '7 out of 41', '28 out of 30',
       '13 out of 15', '6 out of 21', '8 out of 16', '2 out of 6',
       '5 out of 19', '3 out of 11', '17 out of 42', '10 out of 12',
       '8 out of 28', '9 out of 15', '14 out of 22', '18 out of 40',
       '9 out of 17', '12 out of 45', '25 out of 35', '7 out of 15',
       '10 out of 16', 'Upper Basement out of 20', '5 out of 20',
       'Upper Basement out of 40', '5 out of 18', '34 out of 58',
       '4 out of 6', '20 out of 22', '12 out of 19', '15 out of 18',
       '65 out of 78', '6 out of 16', '17 out of 22', '6 out of 24',
       '40 out of 75', '19 out of 38', '15 out of 31', '11 out of 28',
       '10 out of 22', '17 out of 24', '15 out of 19', '9 out of 10',
       '7 out of 12', '8 out of 20', '11 out of 13', '9 out of 19',
       '37 out of 51', '6 out of 11', '8 out of 15', '11 out of 20',
       '10 out of 23', 'Upper Basement out of 10', '7 out of 23',
       '4 out of 11', '17 out of 43', '7 out of 22', '14 out of 18',
       '6 out of 10', '8 out of 12', '3 out of 18', '7 out of 7',
       '14 out of 58', '18 out of 23', '19 out of 19', '13 out of 14',
       '7 out of 11', '11 out of 22', 'Upper Basement out of 30',
       '12 out of 14', '16 out of 31', '12 out of 13', '11 out of 51',
       '2 out of 12', '22 out of 24', '7 out of 14', '5 out of 13',
       '7 out of 21', '14 out of 21', '17 out of 25', '9 out of 14',
       '8 out of 27', '3 out of 6', '17 out of 20', '18 out of 22',
       '1 out of 7', '9 out of 30', '3 out of 8', '11 out of 26',
       '17 out of 27', '4 out of 12', '12 out of 16', '10 out of 24',
       '65 out of 76', '7 out of 9', '17 out of 60', '10 out of 11',
       '18 out of 25', '5 out of 11', '15 out of 17', '15 out of 23',
       '5 out of 17', '3 out of 28', '5 out of 24', '16 out of 32',
       '21 out of 22', '7 out of 13', '9 out of 12', '15 out of 32',
       '18 out of 27', '15 out of 16', '18 out of 45', '15 out of 15',
       '6 out of 14', '1 out of 20', '16 out of 36', '30 out of 44',
       '30 out of 37', '2 out of 9', '12 out of 22', '4 out of 9',
       '2 out of 22', '5 out of 6', '6 out of 18', '35 out of 55',
       '16 out of 29', '30 out of 45', '5 out of 9', '16 out of 25',
       '33 out of 42', '4 out of 16', '13 out of 23', '9 out of 38',
       '6 out of 8', '8 out of 13', '19 out of 30', '10 out of 14',
       '11 out of 24', '9 out of 16', '9 out of 31', '4 out of 15',
       '3 out of 9', '22 out of 30', '3 out of 58', '1 out of 9',
       '53 out of 60', '5 out of 22', '15 out of 22', '19 out of 21',
       '9 out of 40', 'Ground out of 8', '44 out of 75', '8 out of 17',
       '3 out of 14', '12 out of 31', '26 out of 42', '2 out of 45',
       '12 out of 68', '17 out of 36', '10 out of 28', '41 out of 41',
       '14 out of 68', '14 out of 17', '15 out of 20', '46 out of 76',
       '12 out of 20', '20 out of 30', '18 out of 32', '10 out of 25',
       '17 out of 29', '10 out of 31', '10 out of 15', '13 out of 16',
       '8 out of 10', '18 out of 21', '27 out of 58', '1 out of 6',
       '19 out of 25', '3 out of 15', '25 out of 43', '8 out of 14',
       '11 out of 12', '9 out of 21', '10 out of 13', '45 out of 77',
       '18 out of 19', '10 out of 20', '12 out of 29',
       'Lower Basement out of 18', '15 out of 24', '48 out of 68',
       '12 out of 42', '16 out of 22', '35 out of 68', '18 out of 30',
       '11 out of 31', '50 out of 75', '18 out of 26', '12 out of 27',
       '16 out of 20', '24 out of 55', '16 out of 37',
       'Upper Basement out of 7', '6 out of 15', '11 out of 27',
       '11 out of 23', '3 out of 12', '14 out of 15', '23 out of 25',
       '14 out of 48', '29 out of 35', '15 out of 36', '15 out of 25',
       '15 out of 28', '3 out of 36', '8 out of 11', '6 out of 20',
       '23 out of 23', '5 out of 15', '16 out of 18', '2 out of 10',
       '40 out of 50', '25 out of 28', '12 out of 17', '34 out of 40',
       'Upper Basement out of 22', '8 out of 23', '5 out of 21',
       '32 out of 59', '20 out of 32', '9 out of 18', '10 out of 37',
       '25 out of 48', '4 out of 22', '8 out of 18', '11 out of 11',
       '5 out of 23', '60 out of 77', '11 out of 18', '4 out of 20',
       '5 out of 16', '3 out of 13', '30 out of 58', '15 out of 43',
       '7 out of 16', '18 out of 28', '9 out of 55', '11 out of 25',
       '49 out of 55', '7 out of 27', '14 out of 27', '16 out of 27',
       '25 out of 50', '6 out of 30', '21 out of 23', '8 out of 58',
       '20 out of 41', '3 out of 62', '4 out of 13', '7 out of 17',
       '12 out of 21', '28 out of 39', '15 out of 58', '6 out of 23',
       '36 out of 45', '9 out of 28', '6 out of 45', '22 out of 52',
       '10 out of 19', '21 out of 58', '48 out of 54', '7 out of 28',
       '11 out of 15', '19 out of 22', '15 out of 37', '2 out of 17',
       '76 out of 78', '3 out of 10', '20 out of 27', '8 out of 36',
       '14 out of 33', '21 out of 21', '12 out of 25', '18 out of 29',
       '14 out of 35', '7 out of 20', '20 out of 37', '9 out of 35',
       '27 out of 27', '15 out of 60', '19 out of 33', '18 out of 20',
       '13 out of 40', '9 out of 11', '8 out of 22', '6 out of 13',
       '20 out of 31', '27 out of 45', '19 out of 20', '32 out of 46',
       '19 out of 85', '3 out of 23', '34 out of 46', '4 out of 27',
       '19 out of 27', '35 out of 60', '21 out of 33', '25 out of 52',
       '2 out of 24', '24 out of 24', '18 out of 33', '1 out of 10',
       '45 out of 60', '60 out of 71', '36 out of 81', '24 out of 60',
       '16 out of 38', '8 out of 45', 'Ground out of 16', '8 out of 32',
       '10 out of 10', '23 out of 40', '7 out of 18', '8 out of 19',
       '6 out of 17', '16 out of 34', 'Ground out of 12', '6 out of 9',
       'Ground out of 18', '20 out of 25', '3 out of 22', '9 out of 32',
       '26 out of 32', '17 out of 18', '24 out of 25', '19 out of 26',
       '17 out of 19', '1 out of 13', '14 out of 30', '8 out of 9',
       '3 out of 17', 'Lower Basement out of 3', '12 out of 23',
       'Ground out of 9', '1 out of 24', '1 out of 12', '3', 'Ground',
       '15 out of 29', '20 out of 20', '14 out of 29',
       'Lower Basement out of 1', '13 out of 17', '1 out of 14',
       'Upper Basement out of 2', '2 out of 14', '24 out of 31',
       '2 out of 32', '2 out of 16', '9 out of 13', '1 out of 11',
       '6 out of 29', '9 out of 9', '28 out of 31', '1 out of 15',
       'Ground out of 14', '2 out of 11', '19 out of 31', '1 out of 16',
       '25 out of 32', '11 out of 16', '11 out of 17',
       'Upper Basement out of 3', '4 out of 24', '1 out of 19',
       '7 out of 30', '16 out of 19', 'Upper Basement out of 5',
       'Ground out of 13', '2 out of 25', '23 out of 30', '4 out of 30',
       '13 out of 25', '23 out of 35', 'Ground out of 10', '5 out of 34',
       '20 out of 35', '1', '4 out of 31', '4 out of 26', '24 out of 33',
       '4 out of 17', '1 out of 35', '11 out of 35', 'Ground out of 15',
       'Ground out of 27', '15 out of 30', '12 out of 30', '23 out of 34'],
      dtype=object)

In [29]:
# reemplazar valores de Floor que contienen 'Ground' por cero
df['Floor'] = df['Floor'].str.replace('Ground', '0')
df.Floor.unique()

array(['0 out of 2', '1 out of 3', '1 out of 2', '0 out of 1',
       '0 out of 4', '1 out of 4', '1 out of 1', '0 out of 3',
       '2 out of 3', '4 out of 5', '2 out of 2', '2 out of 5',
       '4 out of 14', '3 out of 3', '5 out of 5', '4 out of 4',
       '7 out of 8', '2 out of 4', '3 out of 4', '1 out of 5',
       '8 out of 5', '0 out of 6', '2 out of 1',
       'Upper Basement out of 4', '0 out of 5', '3 out of 5',
       '11 out of 19', '5 out of 10', '11 out of 14',
       'Lower Basement out of 2', '2 out of 7', '4 out of 10',
       '7 out of 10', '2 out of 13', '6 out of 7', '4 out of 7',
       '14 out of 14', '43 out of 78', '2 out of 8', '13 out of 18',
       '5 out of 12', '18 out of 24', '3 out of 7', '17 out of 31',
       '11 out of 21', '7 out of 19', '14 out of 23', '9 out of 20',
       'Upper Basement out of 9', '19 out of 24', '3 out of 21',
       '1 out of 22', '8 out of 8', '6 out of 12', '4 out of 58',
       'Upper Basement out of 16', '60 out of 66', '34 out of 48',
       '5 out of 8', '5 out of 14', '14 out of 40', '5 out of 7',
       '9 out of 22', '12 out of 18', '26 out of 44', '1 out of 8',
       '25 out of 42', '25 out of 41', '53 out of 78', '0 out of 7',
       '14 out of 20', '13 out of 20', '16 out of 23', '10 out of 18',
       '39 out of 60', '16 out of 21', '10 out of 32', '4 out of 8',
       '12 out of 24', '32 out of 41', '3 out of 30', '13 out of 21',
       '9 out of 29', '47 out of 89', '7 out of 41', '28 out of 30',
       '13 out of 15', '6 out of 21', '8 out of 16', '2 out of 6',
       '5 out of 19', '3 out of 11', '17 out of 42', '10 out of 12',
       '8 out of 28', '9 out of 15', '14 out of 22', '18 out of 40',
       '9 out of 17', '12 out of 45', '25 out of 35', '7 out of 15',
       '10 out of 16', 'Upper Basement out of 20', '5 out of 20',
       'Upper Basement out of 40', '5 out of 18', '34 out of 58',
       '4 out of 6', '20 out of 22', '12 out of 19', '15 out of 18',
       '65 out of 78', '6 out of 16', '17 out of 22', '6 out of 24',
       '40 out of 75', '19 out of 38', '15 out of 31', '11 out of 28',
       '10 out of 22', '17 out of 24', '15 out of 19', '9 out of 10',
       '7 out of 12', '8 out of 20', '11 out of 13', '9 out of 19',
       '37 out of 51', '6 out of 11', '8 out of 15', '11 out of 20',
       '10 out of 23', 'Upper Basement out of 10', '7 out of 23',
       '4 out of 11', '17 out of 43', '7 out of 22', '14 out of 18',
       '6 out of 10', '8 out of 12', '3 out of 18', '7 out of 7',
       '14 out of 58', '18 out of 23', '19 out of 19', '13 out of 14',
       '7 out of 11', '11 out of 22', 'Upper Basement out of 30',
       '12 out of 14', '16 out of 31', '12 out of 13', '11 out of 51',
       '2 out of 12', '22 out of 24', '7 out of 14', '5 out of 13',
       '7 out of 21', '14 out of 21', '17 out of 25', '9 out of 14',
       '8 out of 27', '3 out of 6', '17 out of 20', '18 out of 22',
       '1 out of 7', '9 out of 30', '3 out of 8', '11 out of 26',
       '17 out of 27', '4 out of 12', '12 out of 16', '10 out of 24',
       '65 out of 76', '7 out of 9', '17 out of 60', '10 out of 11',
       '18 out of 25', '5 out of 11', '15 out of 17', '15 out of 23',
       '5 out of 17', '3 out of 28', '5 out of 24', '16 out of 32',
       '21 out of 22', '7 out of 13', '9 out of 12', '15 out of 32',
       '18 out of 27', '15 out of 16', '18 out of 45', '15 out of 15',
       '6 out of 14', '1 out of 20', '16 out of 36', '30 out of 44',
       '30 out of 37', '2 out of 9', '12 out of 22', '4 out of 9',
       '2 out of 22', '5 out of 6', '6 out of 18', '35 out of 55',
       '16 out of 29', '30 out of 45', '5 out of 9', '16 out of 25',
       '33 out of 42', '4 out of 16', '13 out of 23', '9 out of 38',
       '6 out of 8', '8 out of 13', '19 out of 30', '10 out of 14',
       '11 out of 24', '9 out of 16', '9 out of 31', '4 out of 15',
       '3 out of 9', '22 out of 30', '3 out of 58', '1 out of 9',
       '53 out of 60', '5 out of 22', '15 out of 22', '19 out of 21',
       '9 out of 40', '0 out of 8', '44 out of 75', '8 out of 17',
       '3 out of 14', '12 out of 31', '26 out of 42', '2 out of 45',
       '12 out of 68', '17 out of 36', '10 out of 28', '41 out of 41',
       '14 out of 68', '14 out of 17', '15 out of 20', '46 out of 76',
       '12 out of 20', '20 out of 30', '18 out of 32', '10 out of 25',
       '17 out of 29', '10 out of 31', '10 out of 15', '13 out of 16',
       '8 out of 10', '18 out of 21', '27 out of 58', '1 out of 6',
       '19 out of 25', '3 out of 15', '25 out of 43', '8 out of 14',
       '11 out of 12', '9 out of 21', '10 out of 13', '45 out of 77',
       '18 out of 19', '10 out of 20', '12 out of 29',
       'Lower Basement out of 18', '15 out of 24', '48 out of 68',
       '12 out of 42', '16 out of 22', '35 out of 68', '18 out of 30',
       '11 out of 31', '50 out of 75', '18 out of 26', '12 out of 27',
       '16 out of 20', '24 out of 55', '16 out of 37',
       'Upper Basement out of 7', '6 out of 15', '11 out of 27',
       '11 out of 23', '3 out of 12', '14 out of 15', '23 out of 25',
       '14 out of 48', '29 out of 35', '15 out of 36', '15 out of 25',
       '15 out of 28', '3 out of 36', '8 out of 11', '6 out of 20',
       '23 out of 23', '5 out of 15', '16 out of 18', '2 out of 10',
       '40 out of 50', '25 out of 28', '12 out of 17', '34 out of 40',
       'Upper Basement out of 22', '8 out of 23', '5 out of 21',
       '32 out of 59', '20 out of 32', '9 out of 18', '10 out of 37',
       '25 out of 48', '4 out of 22', '8 out of 18', '11 out of 11',
       '5 out of 23', '60 out of 77', '11 out of 18', '4 out of 20',
       '5 out of 16', '3 out of 13', '30 out of 58', '15 out of 43',
       '7 out of 16', '18 out of 28', '9 out of 55', '11 out of 25',
       '49 out of 55', '7 out of 27', '14 out of 27', '16 out of 27',
       '25 out of 50', '6 out of 30', '21 out of 23', '8 out of 58',
       '20 out of 41', '3 out of 62', '4 out of 13', '7 out of 17',
       '12 out of 21', '28 out of 39', '15 out of 58', '6 out of 23',
       '36 out of 45', '9 out of 28', '6 out of 45', '22 out of 52',
       '10 out of 19', '21 out of 58', '48 out of 54', '7 out of 28',
       '11 out of 15', '19 out of 22', '15 out of 37', '2 out of 17',
       '76 out of 78', '3 out of 10', '20 out of 27', '8 out of 36',
       '14 out of 33', '21 out of 21', '12 out of 25', '18 out of 29',
       '14 out of 35', '7 out of 20', '20 out of 37', '9 out of 35',
       '27 out of 27', '15 out of 60', '19 out of 33', '18 out of 20',
       '13 out of 40', '9 out of 11', '8 out of 22', '6 out of 13',
       '20 out of 31', '27 out of 45', '19 out of 20', '32 out of 46',
       '19 out of 85', '3 out of 23', '34 out of 46', '4 out of 27',
       '19 out of 27', '35 out of 60', '21 out of 33', '25 out of 52',
       '2 out of 24', '24 out of 24', '18 out of 33', '1 out of 10',
       '45 out of 60', '60 out of 71', '36 out of 81', '24 out of 60',
       '16 out of 38', '8 out of 45', '0 out of 16', '8 out of 32',
       '10 out of 10', '23 out of 40', '7 out of 18', '8 out of 19',
       '6 out of 17', '16 out of 34', '0 out of 12', '6 out of 9',
       '0 out of 18', '20 out of 25', '3 out of 22', '9 out of 32',
       '26 out of 32', '17 out of 18', '24 out of 25', '19 out of 26',
       '17 out of 19', '1 out of 13', '14 out of 30', '8 out of 9',
       '3 out of 17', 'Lower Basement out of 3', '12 out of 23',
       '0 out of 9', '1 out of 24', '1 out of 12', '3', '0',
       '15 out of 29', '20 out of 20', '14 out of 29',
       'Lower Basement out of 1', '13 out of 17', '1 out of 14',
       'Upper Basement out of 2', '2 out of 14', '24 out of 31',
       '2 out of 32', '2 out of 16', '9 out of 13', '1 out of 11',
       '6 out of 29', '9 out of 9', '28 out of 31', '1 out of 15',
       '0 out of 14', '2 out of 11', '19 out of 31', '1 out of 16',
       '25 out of 32', '11 out of 16', '11 out of 17',
       'Upper Basement out of 3', '4 out of 24', '1 out of 19',
       '7 out of 30', '16 out of 19', 'Upper Basement out of 5',
       '0 out of 13', '2 out of 25', '23 out of 30', '4 out of 30',
       '13 out of 25', '23 out of 35', '0 out of 10', '5 out of 34',
       '20 out of 35', '1', '4 out of 31', '4 out of 26', '24 out of 33',
       '4 out of 17', '1 out of 35', '11 out of 35', '0 out of 15',
       '0 out of 27', '15 out of 30', '12 out of 30', '23 out of 34'],
      dtype=object)

In [31]:
# separar Floor en dos columnas: Current Floor y Total Floor
df[['Current_Floor', 'Total_Floors']] = (
    df['Floor'].str.extract(r'(\d+)\s*out of\s*(\d+)')
)

df.sample(5)

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact,Current_Floor,Total_Floors
1481,2022-07-09,2,70000,760,9 out of 22,Carpet Area,"L&T Emerald Isle, Powai",Mumbai,Semi-Furnished,Bachelors/Family,2,Contact Agent,9,22
4398,2022-07-06,3,15000,2000,0 out of 2,Super Area,Thumukunta,Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner,0,2
2237,2022-06-30,1,9000,400,1 out of 1,Super Area,"Laxminarayana Layout, Munnekollal",Bangalore,Semi-Furnished,Bachelors,1,Contact Owner,1,1
113,2022-07-06,3,12000,800,0 out of 1,Super Area,"Parnashree Lake, Behala",Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner,0,1
3227,2022-06-29,2,18000,1300,3 out of 3,Super Area,Velachery,Chennai,Unfurnished,Bachelors/Family,2,Contact Owner,3,3

In [32]:
# convertir valores de current y total Floor a numerico
df['Current_Floor'] = pd.to_numeric(df['Current_Floor'])
df['Total_Floors'] = pd.to_numeric(df['Total_Floors'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Posted On          4746 non-null   datetime64[ns]
 1   BHK                4746 non-null   int64
 2   Rent               4746 non-null   int64
 3   Size               4746 non-null   int64
 4   Floor              4746 non-null   object
 5   Area Type          4746 non-null   object
 6   Area Locality      4746 non-null   object
 7   City               4746 non-null   object
 8   Furnishing Status  4746 non-null   object
 9   Tenant Preferred   4746 non-null   object
 10  Bathroom           4746 non-null   int64
 11  Point of Contact   4746 non-null   object
 12  Current_Floor      4708 non-null   float64
 13  Total_Floors       4708 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(4), object(7)
memory usage: 519.2+ KB

In [33]:
# detectar registros inconsistentes
floors_invalid = df[df['Current_Floor'] > df['Total_Floors']]
floors_invalid

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact,Current_Floor,Total_Floors
105,2022-06-06,1,6000,600,8 out of 5,Carpet Area,Pratiraksha Nagar,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner,8.0,5.0
161,2022-06-27,2,10000,450,2 out of 1,Carpet Area,Behala,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner,2.0,1.0

In [34]:
# eliminar registros inconsistentes
df = df[df['Current_Floor'] <= df['Total_Floors']]

floors_invalid = df[df['Current_Floor'] > df['Total_Floors']]
floors_invalid

Empty DataFrame
Columns: [Posted On, BHK, Rent, Size, Floor, Area Type, Area Locality, City, Furnishing Status, Tenant Preferred, Bathroom, Point of Contact, Current_Floor, Total_Floors]
Index: []

Floor
Floor
1 out of 2      379
0 out of 2      350
2 out of 3      312
2 out of 4      308
1 out of 3      293
               ...
20 out of 30      1
46 out of 76      1
14 out of 68      1
41 out of 41      1
11 out of 28      1
Name: count, Length: 459, dtype: int64

Area Type
Area Type
Super Area     2438
Carpet Area    2266
Built Area        2
Name: count, dtype: int64

Area Locality
Area Locality
Bandra West                              37
Gachibowli                               29
Electronic City                          24
Miyapur, NH 9                            22
Velachery                                22
                                         ..
Sai Raghavendra Colony, uppal             1
Balapur                                   1
Sikh Apartmentge, NH 7                    1
Adibatla                                  1
Modi Paradise, Hayathnagar, Hyderabad     1
Name: count, Length: 2218, dtype: int64

City
City
Mumbai       956
Chennai      886
Bangalore    883
Hyderabad    858
Delhi        603
Kolkata      520
Name: count, dtype: int64

Furnishing Status
Furnishing Status
Semi-Furnished    2235
Unfurnished       1797
Furnished          674
Name: count, dtype: int64

Tenant Preferred
Tenant Preferred
Bachelors/Family    3417
Bachelors            826
Family               463
Name: count, dtype: int64

Point of Contact
Point of Contact
Contact Owner      3192
Contact Agent      1513
Contact Builder       1
Name: count, dtype: int64